class Permission:
    FOLLOW = 1
    RATE = 2
    WRITE_REVIEWS = 3
    MODERATE_REVIEWS = 4
    ADMINISTER = 5


class Role:
    ROLES = dict()

    ROLE_USER = 'User'
    ROLE_MODERATOR = 'Moderator'
    ROLE_ADMIN = 'Admin'
    DEFAULT_ROLE = ROLE_USER

    ROLE_USER_PERMS = (Permission.FOLLOW, Permission.RATE, Permission.WRITE_REVIEWS)
    ROLE_MODERATOR_PERMS = ROLE_USER_PERMS + (Permission.MODERATE_REVIEWS,)
    ROLE_ADMIN_PERMS = ROLE_MODERATOR_PERMS + (Permission.ADMINISTER,)

    ROLES[ROLE_USER] = ROLE_USER_PERMS
    ROLES[ROLE_MODERATOR] = ROLE_MODERATOR_PERMS
    ROLES[ROLE_ADMIN] = ROLE_ADMIN_PERMS
